# Generated by Django 4.1.7 on 2023-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_choice',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('FINANCE', 'FIN'), ('POLITICS', 'POL'), ('ROMANCE', 'ROM'), ('SPORT', 'SPO'), ('ENTERTAINMENT', 'ENT')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('NORWAY', 'NOR'), ('FINLAND', 'FIN'), ('ENGLAND', 'ENG'), ('GHANA', 'GHA')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'A'), ('BORROWED', 'B')], default=None, max_length=10),
        ),
    ]
